# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Quiz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Quiz

  pod 'EVTopTabBar'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth' 
  pod 'ReachabilitySwift'
  pod 'GoogleSignIn'
  pod 'Firebase/Database'
  pod 'Google-Mobile-Ads-SDK'
  pod 'FBAudienceNetwork'
  pod 'FirebaseAnalytics'
  pod 'SwiftyJWT'
  pod 'FacebookSDK'
  pod 'FacebookSDK/LoginKit'
  pod 'FacebookSDK/ShareKit'
  pod 'FacebookSDK/PlacesKit'

  target 'QuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuizUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
